### ISSUE TITLE
Add a general way to introduce data to the Optimizer for Cutting Bars

### ISSUE THREAD

**Issue by WilmerTV** [TerVarSoft/LongCalculator#47]
Add optimizer for cutting bars generally

**Comment by MirkoTV** [comment]
Some ideas here:
- This should be the MOST GENERAL way to introduce data to the app.  Should not be dependent of the type of the profile(jamba, riel, gancho etc)
- We need a new view for this.
-  Every cut should be matched to an identifier name (like the name of the window or the name of the door, etc)

Need to discuss some points:
- We need some way to disable the "profile select picker" in the calculator view when the data has come from this new view. How ?? I think we can add a mode variable to the url of the calcutation view like http://localhost:8080?mode=windowsMode  or http://localhost:8080?mode=generalMode
- How is going to work the save button on each mode?

**Comment by MirkoTV** [comment]
@WilmerTV  Could you upload a preview of the view as soon as you have an idea?, just open a comment and drag and drop the image.
